version: '3'
services:
  web:
    build:
      context: .
      dockerfile: WebDockerfile
    ports:
    - "5000:5000"
    volumes:
       - ./:/code
    expose:
    - "5000"
    environment:
    - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
    - CELERY_RESULT_BACKEND=database
    - CELERY_RESULT_DBURI=couchdb://couchdb:5984
    links:
    - rabbitmq
    - couchdb
  worker:
    build:
      context: .
      dockerfile: WorkerDockerfile
    environment:
    - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
    - CELERY_RESULT_BACKEND=database
    - CELERY_RESULT_DBURI=couchdb://couchdb:5984
    links:
    - rabbitmq
    - couchdb
  rabbitmq:
    image: rabbitmq
  couchdb:
    image: couchdb
    ports:
    - "5984:5984"
